block_cipher = None
a = Analysis(['MTrack_Qt.py'],
        pathex=['/Users/linzhang/Documents/Engineering/Python/M-Track-master'],
        binaries=None,
        datas=None,
        hiddenimports=[],
        hookspath=[('/Users/linzhang/Documents/Engineering/Python/M-Track-master/')],
        runtime_hooks=None,
        excludes=None,
        ciper=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
        cipher=block_cipher)
exe = EXE(pyz, ...)
coll = COLLECT(...)